# Generated by Django 4.2.14 on 2024-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.PositiveIntegerField(verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='views_count',
            field=models.PositiveIntegerField(verbose_name='количество просмотров'),
        ),
    ]
