# Generated by Django 4.2.14 on 2024-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
